version: 1.0.{build}
configuration: Release

skip_tags: true
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal